# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            "Jason Bilyeu's Blog" 
tagline:          'A test-minded software architect delving into the world of microservices with Spring Boot and responsive UI design with AngularJS'
description:      'A test-minded software architect delving into the world of microservices with Spring Boot and responsive UI design with AngularJS' 
url:              http://hyde.getpoole.com
baseurl:          /hyde

author:
  name:           'Jason Bilyeu' 
  url:            https://linkedin.com
email:            jasonbilyeu@ymail.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jasonbilyeu/jasonbilyeu.github.io 
